M48
; DRILL file {KiCad 9.0.3-1.fc42} date 2025-11-28T05:18:46+0000
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-11-28T05:18:46+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3-1.fc42
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X3.6089Y-2.3248
X3.7998Y-2.3248
T2
X3.597Y-2.2055
X3.8116Y-2.2055
M30
